#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DaysTaxi.Droid.Resource", IsApplication=true)]

namespace DaysTaxi.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::DaysTaxi.Droid.Resource.String.library_name;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::DaysTaxi.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::DaysTaxi.Droid.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroidN.Resource.String.ApplicationName = global::DaysTaxi.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroidN.Resource.String.Hello = global::DaysTaxi.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public const int common_google_signin_btn_text_dark = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int common_google_signin_btn_text_dark_default = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int common_google_signin_btn_text_dark_disabled = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int common_google_signin_btn_text_dark_focused = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_google_signin_btn_text_dark_pressed = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_signin_btn_text_light = 2130968586;
			
			// aapt resource value: 0x7f040004
			public const int common_google_signin_btn_text_light_default = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int common_google_signin_btn_text_light_disabled = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_signin_btn_text_light_focused = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_google_signin_btn_text_light_pressed = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int theme_holo_background = 2130968584;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Icon = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080028
			public const int addCarBtn = 2131230760;
			
			// aapt resource value: 0x7f080000
			public const int adjust_height = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int adjust_width = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int auto = 2131230726;
			
			// aapt resource value: 0x7f08001e
			public const int birth_date = 2131230750;
			
			// aapt resource value: 0x7f080009
			public const int carNameTxt = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int classSpinner = 2131230730;
			
			// aapt resource value: 0x7f080013
			public const int classTxt = 2131230739;
			
			// aapt resource value: 0x7f080025
			public const int clientSignupBtn = 2131230757;
			
			// aapt resource value: 0x7f080022
			public const int confLink = 2131230754;
			
			// aapt resource value: 0x7f080017
			public const int cprofText = 2131230743;
			
			// aapt resource value: 0x7f080007
			public const int dark = 2131230727;
			
			// aapt resource value: 0x7f08001d
			public const int date = 2131230749;
			
			// aapt resource value: 0x7f080015
			public const int deleteBtn = 2131230741;
			
			// aapt resource value: 0x7f080026
			public const int driverSignupBtn = 2131230758;
			
			// aapt resource value: 0x7f080014
			public const int editBtn = 2131230740;
			
			// aapt resource value: 0x7f080018
			public const int email = 2131230744;
			
			// aapt resource value: 0x7f08001b
			public const int first_name = 2131230747;
			
			// aapt resource value: 0x7f080003
			public const int icon_only = 2131230723;
			
			// aapt resource value: 0x7f08001c
			public const int last_name = 2131230748;
			
			// aapt resource value: 0x7f080008
			public const int light = 2131230728;
			
			// aapt resource value: 0x7f08000f
			public const int linearLayout1 = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int linearLayout2 = 2131230737;
			
			// aapt resource value: 0x7f080024
			public const int loginBtn = 2131230756;
			
			// aapt resource value: 0x7f080027
			public const int myButton = 2131230759;
			
			// aapt resource value: 0x7f080012
			public const int nameTxt = 2131230738;
			
			// aapt resource value: 0x7f080002
			public const int none = 2131230722;
			
			// aapt resource value: 0x7f080019
			public const int pass = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int phone = 2131230746;
			
			// aapt resource value: 0x7f080010
			public const int photoImg = 2131230736;
			
			// aapt resource value: 0x7f08001f
			public const int regBtn = 2131230751;
			
			// aapt resource value: 0x7f08000e
			public const int relativeLayout1 = 2131230734;
			
			// aapt resource value: 0x7f080023
			public const int resendBtn = 2131230755;
			
			// aapt resource value: 0x7f080016
			public const int scrollView1 = 2131230742;
			
			// aapt resource value: 0x7f08000c
			public const int selImgBtn = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int selectCarPhotoView = 2131230731;
			
			// aapt resource value: 0x7f080004
			public const int standard = 2131230724;
			
			// aapt resource value: 0x7f08000d
			public const int submitBtn = 2131230733;
			
			// aapt resource value: 0x7f080021
			public const int textView1 = 2131230753;
			
			// aapt resource value: 0x7f080020
			public const int vehiclesBtn = 2131230752;
			
			// aapt resource value: 0x7f080029
			public const int vehsListView = 2131230761;
			
			// aapt resource value: 0x7f080005
			public const int wide = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddVehicleLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CarRowLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ClientProfile = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ClientSignup = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DriverProfile = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int HomePage = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int LoadScreen = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MyVehicles = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050012
			public const int ApplicationName = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int Hello = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int app_name = 2131034133;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_enable_button = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_enable_text = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_enable_title = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_install_button = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_text = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_install_title = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_notification_ticker = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_unknown_issue = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_unsupported_text = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_update_button = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_text = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_update_title = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_updating_text = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_wear_update_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_open_on_phone = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int common_signin_button_text = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_signin_button_text_long = 2131034127;
			
			// aapt resource value: 0x7f050014
			public const int hello = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int library_name = 2131034131;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
